export enum RouteEnum {
  PLAYER = '/player/:name',
  SERVER = '/server',
  ROOM = '/room/:roomId',
  LOGIN = '/login',
  LOGS = '/logs',
  GAME = '/game',
  DECKS = '/decks',
  DECK = '/deck',
  ACCOUNT = '/account',
  SOCIAL = '/social',
  ADMINISTRATION = '/administration',
  REPLAYS = '/replays',
  INITIALIZE = '/initialize',
  UNSUPPORTED = '/unsupported',
}
